### PR TITLE
Update maintainer list

### PR DESCRIPTION
**Pull request by Anthchirp**
@ndevenish @rjgildea if you could just add a comment saying you're happy to take this on
@tschoonj I assume you don't mind I took you off :smile: 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

### CODE REVIEW

**Comment by Anthchirp** [comment]
@conda-forge-admin, please rerender

**Comment by rjgildea** [comment]
👍

**Comment by tschoonj** [comment]
LGTM

**Comment by ndevenish** [comment]
👍

**Pull request merged**
